version: "3.9"  # optional since v1.27.0
services:
  ui:
    build: ./ui
    environment:
      CHOKIDAR_USEPOLLING: "true"
    volumes:
      - ./ui:/usr/src
      - ui_node_modules:/ui/node_modules
    ports:
      - "3000:3000"

  api:
    build: ./api
    volumes:
      - ./api:/go/src/github.com/badis/hackathon
    ports:
      - "5000:5000"
    links:
      - db

  db:
    build: ./db
    volumes:
      - db_pgdata:/var/lib/postgresql/data
    ports:
      - "5432"
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=0000
      - PGDATA=/var/lib/postgresql/data

  adminer:
    image: adminer
    restart: always
    ports:
      - 8000:8080

volumes:
  ui_node_modules:
  db_pgdata:

