apiVersion: apps/v1
kind: Deployment
metadata:
  name: hackathon-postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
      - name: postgres
        image: hackathon-postgres-img
        ports:
        - containerPort: 5432

        env:
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: postgres-secret
              key: postgres-user
        - name: POSTGRES_PASSWORD
          valueFrom: 
            secretKeyRef:
              name: postgres-secret
              key: postgres-password
        - name: POSTGRES_DB
          valueFrom: 
            configMapKeyRef:
              name: postgres-configmap
              key: postgres-db

        readinessProbe:
          periodSeconds: 5
          tcpSocket:
            port: 5432
        livenessProbe:
          periodSeconds: 5
          tcpSocket:
            port: 5432
        volumeMounts:
        - mountPath: /var/lib/postgresql/data
          name: ps-data
        resources:
          limits:
            memory: 256Mi
            cpu: 125m
          requests:
            cpu: 70m
            memory: 200Mi
      volumes:
      - name: ps-data
        emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: hackathon-postgres-service
spec:
  type: ClusterIP
  selector:
    app: hackathon-postgres
  ports:
  - name: http
    port: 5432
    targetPort: 5432