export const VIEW_PATIENT = 'VIEW_PATIENT';
export const ADD_PATIENT = 'ADD_PATIENT';
export const UPDATE_PATIENT = 'UPDATE_PATIENT';
export const DELETE_PATIENT = 'DELETE_PATIENT';
export const LIST_PATIENTS = 'LIST_PATIENTS';
export const ADD_DISEASE = 'ADD_DISEASE';
export const UPDATE_DISEASE = 'UPDATE_DISEASE';
