
@host=http://localhost:5000

###
POST {{host}}/patients
Content-Type: application/json

{
    "firstname": "John",
    "lastname": "Doe",
    "email": "john@example.com",
    "disease_name": "Kiutari",
    "disease_omimid": "qw12s3ee",
    "disease_id": 0
}

###
POST {{host}}/login
Content-Type: application/json

{
    "email": "john@example.com"
}



